### ISSUE TITLE
Getting `environment.getStore(...).getEpoch is not a function`

### ISSUE THREAD

**Issue by LionC** [richardguerre/use-relay-mock-environment#5]
I set up a story following the guide in the README. It typechecks correctly and storybook builds and runs, but when trying to render the actual story, I get:

```
TypeError: environment.getStore(...).getEpoch is not a function
    at FragmentResourceImpl.readWithIdentifier (http://localhost:6006/vendors~main.iframe.bundle.js:77442:45)
    at useFragmentNode (http://localhost:6006/vendors~main.iframe.bundle.js:79413:41)
    at useLazyLoadQueryNode (http://localhost:6006/vendors~main.iframe.bundle.js:79776:26)
    at useLazyLoadQuery (http://localhost:6006/vendors~main.iframe.bundle.js:79645:14)
    at QueryWrapper (http://localhost:6006/main.iframe.bundle.js:2011:95)
    at renderWithHooks (http://localhost:6006/vendors~main.iframe.bundle.js:61843:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors~main.iframe.bundle.js:64669:13)
    at beginWork (http://localhost:6006/vendors~main.iframe.bundle.js:65907:16)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.iframe.bundle.js:50803:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.iframe.bundle.js:50852:16)
```

(`QueryWrapper` being my component).

Investigating this for some seconds, I suspected that this is because this package is one major behind the current version of `relay-test-utils`, which introduced the concept of epochs. I *suspect* that upgrading would fix it, although I do not know which other breaking changes were introduced.

Sadly, this makes the package not usable in a current version setup.

**Comment by joeried** [comment]
I had the same problem. The hints in this issue gave me the idea to use the [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) feature of yarn to resolve "relay-test-utils" to the correct relay version.

I use relay 13.0.2 and therefore the entry in the package.json looks like this:
```
 "resolutions": {
    "relay-test-utils":"^13.0.2"
  }
```

With this, the package seems to work again. However, I have not yet been able to do more extensive testing.
